In [2]:
import numpy as np

In [3]:
#!pip install numpy

In [4]:
list1 = [1,2,3,4]

In [5]:
for i in list1:
    print(i**2)

1
4
9
16


In [6]:
[i**2 for i in list1]

[1, 4, 9, 16]

In [7]:
arr = np.array([1,2,3,4])

In [8]:
arr

array([1, 2, 3, 4])

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr**2

array([ 1,  4,  9, 16])

In [11]:
list5 = [i for i in range(1,101)]

In [12]:
arr5 = np.array(list5)

In [13]:
# %timeit [i**2 for i in list5]

In [14]:
# %timeit arr5**2

In [15]:
arr4 = np.arange(12)

In [16]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
np.sum(arr4)

66

In [18]:
np.min(arr4)

0

In [19]:
np.max(arr4)

11

In [20]:
np.mean(arr4)

5.5

In [21]:
arr4.ndim

1

In [22]:
len(arr4)

12

In [23]:
arr4.size

12

In [24]:
list9 = [1,5.0,"string"]

In [25]:
list9

[1, 5.0, 'string']

In [26]:
np.array([True,False])

array([ True, False])

In [27]:
np.array([True,False,5])

array([1, 0, 5])

In [28]:
np.array([True,False,5,5.0])

array([1., 0., 5., 5.])

In [29]:
np.array([True,False,5,5.0,"strng"])

array(['True', 'False', '5', '5.0', 'strng'], dtype='<U32')

In [30]:
np.ones(15,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [31]:
np.zeros(15,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
arr6 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [33]:
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
type(arr6)

numpy.ndarray

In [35]:
arr6.ndim

2

In [36]:
arr6.size

9

In [37]:
arr6.shape

(3, 3)

In [38]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
arr4.shape

(12,)

In [40]:
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr7 = np.arange(50,150,10)

In [42]:
arr7

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140])

In [43]:
arr7[2]

70

In [44]:
arr7[2:5:2]

array([70, 90])

In [45]:
arr7[-2:-5:-2]

array([130, 110])

In [46]:
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr6[0,1]

2

In [48]:
arr6[1:2,0:2]

array([[4, 5]])

In [49]:
arr6[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [50]:
arr7

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140])

In [51]:
arr7[[0,1,3]]

array([50, 60, 80])

In [52]:
list1

[1, 2, 3, 4]

In [53]:
list((list1[0],list1[1],list1[3]))

[1, 2, 4]

In [54]:
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
np.sum(arr6,axis = 0)

array([12, 15, 18])

In [63]:
np.min(arr6,axis = 0)

array([1, 2, 3])

In [64]:
np.max(arr6,axis = 0)

array([7, 8, 9])

In [67]:
np.mean(arr6,axis = 0,dtype = int)

array([4, 5, 6])

In [66]:
np.average(arr6,axis = 0)

array([4., 5., 6.])

In [68]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
# mask
mask = (arr4 % 2 == 0)

In [73]:
arr4[mask]

array([ 0,  2,  4,  6,  8, 10])

In [74]:
arr4[arr4 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [75]:
### task is to fetch elemnts which are greater than 6

In [76]:
arr4[arr4 > 6]

array([ 7,  8,  9, 10, 11])

In [77]:
### task is to fetch elemnts which are divisible by 2 or 3

In [78]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
arr4[(arr4 % 2 == 0) | (arr4 % 3 == 0)]

array([ 0,  2,  3,  4,  6,  8,  9, 10])

In [82]:
arr4[(arr4 % 2 == 0) & (arr4 % 3 == 0)]

array([0, 6])

In [83]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [86]:
np.where(arr4 % 2 == 0,"Even","Odd")

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd'], dtype='<U4')

In [88]:
arr11 = np.array([-3, 4, 27, 34, -2, 0, -45, -11, 4, 0])

In [89]:
# - if element is > 0, change it to +1 : cond_1

# - if element <= 0, change it to -1.

In [91]:
np.where(arr11>0,1,-1)

array([-1,  1,  1,  1, -1, -1, -1, -1,  1, -1])

In [92]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [95]:
np.all(arr4 == 0)

False

In [96]:
np.any(arr4 == 0)

True