In [ ]:
# 21-07-25, Monday; Naynish Sir.

# Module vs Package vs Libraries:

# Module: it is a fundamental unit of code that performs a specific task.

# Package: contains multiple modules.

# Library: contains xollection of related modules/packages that provides a set of functionality for a specific task.

# NumPy (Numerical Python): is a Python library for working with multidimensional arrays and matrices. It's used for scientific calculations and data analysis. It has fast calcultaions and efficient memory management. Treat it like a calculator for your stastical data. visit: https://numpy.org/


In [1]:
import numpy as np

# !pip install numpy -- for installing it on browser.

In [7]:
list1 = [1, 2, 3, 4] #try with map in future.
# print(list1)
# for i in list1:
    # list1[i] = i **2
    # print(i ** 2)

# print(list1)

In [8]:
[i ** 2 for i in list1]

[1, 4, 9, 16]

In [11]:
# List in numpy is called Array.

arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [13]:
type(arr)

numpy.ndarray

In [15]:
# Sq. in numpy
# Vectorization in NumPy refers to the process of applying operations to entire arrays at once, rather than iterating through individual elements using explicit Python loops.

arr ** 2

array([ 1,  4,  9, 16])

In [17]:
list2 = [i for i in range(1, 101)]
# list2

In [19]:
arr2 = np.array([i for i in range(1, 101)])

In [20]:
# magic commands in Python. %timeit
%timeit [i ** 2 for i in list2]

6.38 μs ± 380 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [23]:
%timeit arr2 ** 2

719 ns ± 52 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [25]:
arr3 = np.arange(12)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
np.sum(arr3)

np.int64(66)

In [29]:
np.min(arr3)

np.int64(0)

In [30]:
np.mean(arr3)

np.float64(5.5)

In [31]:
np.max(arr3)

np.int64(11)

In [32]:
arr3.ndim #returns array dimention.

1

In [33]:
len(arr3) #wont work on multi dimentional array, only 1d

12

In [35]:
arr3.size #works on multi dimentional arrays too.

12

In [39]:
np.array([True, False])

array([ True, False])

In [41]:
np.array([True, False, 5])

array([1, 0, 5])

In [42]:
np.array([True, False, 5, 5.5])

array([1. , 0. , 5. , 5.5])

In [43]:
np.array([True, False, 5, 5.5, "py"])

array(['True', 'False', '5', '5.5', 'py'], dtype='<U32')

In [44]:
# Precidence: str > float > int > bool

In [45]:
np.ones(10, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [46]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
arr4 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

arr4 #2D Array.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
type(arr4)

numpy.ndarray

In [51]:
arr4.ndim

2

In [52]:
arr4.size

12

In [53]:
arr4.shape

(3, 4)

In [54]:
arr5 = np.arange(50, 150, 10)

In [55]:
arr5

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140])

In [56]:
arr5[3]

np.int64(80)

In [57]:
arr5[2: 5] #end is excluded; [2 : 5 : 2] for alternate or jump.

array([70, 80, 90])

In [64]:
arr5[-1 : -5 : -2]

array([140, 120])

In [65]:
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
arr4[0,1] #row: col, like chess e4, e5 etc.

np.int64(2)

In [67]:
arr4[0,1:3]

array([2, 3])

In [76]:
arr4[1 : 2, 0: 2]

array([[5, 6]])

In [77]:
# get: 7,8 and 11,12
arr4[1 : 3, 2 : 4]

array([[ 7,  8],
       [11, 12]])

In [78]:
arr5

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140])

In [79]:
arr5[[0, 1, 3]] #getting specific values.

array([50, 60, 80])

In [80]:
[list1]

[[1, 2, 3, 4]]

In [81]:
[list1[0], list1[1], list1[3]] #can use list() too.

[1, 2, 4]