In [82]:
# 21-07-25, Monday; Naynish Sir.

# Module vs Package vs Libraries:

# Module: it is a fundamental unit of code that performs a specific task.

# Package: contains multiple modules.

# Library: contains xollection of related modules/packages that provides a set of functionality for a specific task.

# NumPy (Numerical Python): is a Python library for working with multidimensional arrays and matrices. It's used for scientific calculations and data analysis. It has fast calcultaions and efficient memory management. Treat it like a calculator for your stastical data. visit: https://numpy.org/


In [83]:
import numpy as np

# !pip install numpy -- for installing it on browser.

In [84]:
list1 = [1, 2, 3, 4] #try with map in future.
# print(list1)
# for i in list1:
    # list1[i] = i **2
    # print(i ** 2)

# print(list1)

In [85]:
[i ** 2 for i in list1]

[1, 4, 9, 16]

In [86]:
# List in numpy is called Array.

arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [87]:
type(arr)

numpy.ndarray

In [88]:
# Sq. in numpy
# Vectorization in NumPy refers to the process of applying operations to entire arrays at once, rather than iterating through individual elements using explicit Python loops.

arr ** 2

array([ 1,  4,  9, 16])

In [89]:
list2 = [i for i in range(1, 101)]
# list2

In [90]:
arr2 = np.array([i for i in range(1, 101)])

In [91]:
# magic commands in Python. %timeit
# %timeit [i ** 2 for i in list2]

6.96 μs ± 920 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [92]:
# %timeit arr2 ** 2

689 ns ± 34.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [93]:
arr3 = np.arange(12)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
np.sum(arr3)

np.int64(66)

In [95]:
np.min(arr3)

np.int64(0)

In [96]:
np.mean(arr3)

np.float64(5.5)

In [97]:
np.max(arr3)

np.int64(11)

In [98]:
arr3.ndim #returns array dimention.

1

In [99]:
len(arr3) #wont work on multi dimentional array, only 1d

12

In [100]:
arr3.size #works on multi dimentional arrays too.

12

In [101]:
np.array([True, False])

array([ True, False])

In [102]:
np.array([True, False, 5])

array([1, 0, 5])

In [103]:
np.array([True, False, 5, 5.5])

array([1. , 0. , 5. , 5.5])

In [104]:
np.array([True, False, 5, 5.5, "py"])

array(['True', 'False', '5', '5.5', 'py'], dtype='<U32')

In [105]:
# Precidence: str > float > int > bool

In [106]:
np.ones(10, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [107]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [108]:
arr4 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

arr4 #2D Array.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:
type(arr4)

numpy.ndarray

In [110]:
arr4.ndim

2

In [111]:
arr4.size

12

In [112]:
arr4.shape

(3, 4)

In [113]:
arr5 = np.arange(50, 150, 10)

In [114]:
arr5

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140])

In [115]:
arr5[3]

np.int64(80)

In [116]:
arr5[2: 5] #end is excluded; [2 : 5 : 2] for alternate or jump.

array([70, 80, 90])

In [117]:
arr5[-1 : -5 : -2]

array([140, 120])

In [118]:
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [119]:
arr4[0,1] #row: col, like chess e4, e5 etc.

np.int64(2)

In [120]:
arr4[0,1:3]

array([2, 3])

In [121]:
arr4[1 : 2, 0: 2]

array([[5, 6]])

In [122]:
# get: 7,8 and 11,12
arr4[1 : 3, 2 : 4]

array([[ 7,  8],
       [11, 12]])

In [123]:
arr5

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140])

In [124]:
arr5[[0, 1, 3]] #getting specific values.

array([50, 60, 80])

In [125]:
[list1]

[[1, 2, 3, 4]]

In [126]:
[list1[0], list1[1], list1[3]] #can use list() too.

[1, 2, 4]

In [128]:
# 22-07-26, Monday;

arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [131]:
np.sum(arr4, axis = 0) # 0 is for column.

array([15, 18, 21, 24])

In [132]:
np.sum(arr4, axis = 1) # 1 is for row.

array([10, 26, 42])

In [133]:
np.min(arr4, axis = 0) # 0 is for column.

array([1, 2, 3, 4])

In [134]:
np.max(arr4, axis = 0) # 0 is for column.

array([ 9, 10, 11, 12])

In [137]:
np.mean(arr4, axis = 0, dtype = int) # 0 is for column.

array([5, 6, 7, 8])

In [136]:
np.average(arr4, axis = 0) # 0 is for column.

array([5., 6., 7., 8.])

In [139]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [142]:
# mask: returns T or F, conditioning in NumPy.
mask = (arr3 % 2 == 0)

In [143]:
arr3[mask]

array([ 0,  2,  4,  6,  8, 10])

In [144]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [145]:
# Get elements > 6
gt6 = (arr3 > 6)

In [146]:
arr3[gt6]

array([ 7,  8,  9, 10, 11])

In [152]:
# get elements divisible by 2 and 3.
db2o3 = arr3[(arr3 % 2 == 0) & (arr3 % 3 == 0)] # & for "and", | for "or"

In [153]:
arr3[db2o3]

array([0, 6])

In [155]:
eo = np.where(arr3 % 2 == 0, "Even", "Odd")
eo

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd'], dtype='<U4')

In [157]:
arr6 = np.array([-3, 4, 27, 34, -2, 0, -45, -11, 4, 0])
arr6

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [159]:
#  if element > 0, change it to +1 : cond_1
#  if element <= 0 change it to -1
cond_1 = np.where(arr6 > 0, 1, -1)
cond_1

array([-1,  1,  1,  1, -1, -1, -1, -1,  1, -1])

In [160]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [161]:
np.all(arr3 == 0) # all is like "and", any and all are used to get Null, 0 values, here it's given by None.

np.False_

In [162]:
np.any(arr3 == 0) # any is like "or"

np.True_